# Demonstração

In [1]:
import numpy as np
from sklearn.impute import KNNImputer

In [2]:
X = [[3, 4, 4], [np.nan, 6, 5], [7, 8, np.nan], [8, 8, 7]]

X

[[3, 4, 4], [nan, 6, 5], [7, 8, nan], [8, 8, 7]]

[3, 4, 3] <-
[5.5, 6, 5] <-
[1, 2, 4]
[8, 8, 7]

In [3]:
imputer = KNNImputer(n_neighbors=1)
imputer.fit_transform(X)

array([[3., 4., 4.],
       [3., 6., 5.],
       [7., 8., 7.],
       [8., 8., 7.]])

# Exercício:

Realizar o Data Inputation utilizando o dataset abaixo para os seguintes casos:

- Valor arbitrário: -100.000.000
- Mediana
- Média
- End of Tail (em +3sigma)
- KNN Inputer

**Dica**: Cuidado para não utilizar o mesmo dataset nos diferentes exercícios

In [4]:
# knn imputation transform for the horse colic dataset
from numpy import isnan
from pandas import read_csv

# Carrega  dataset
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/horse-colic.csv'
df = read_csv(url, header=None, na_values='?')

df

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,55.0,65.0,NaN,NaN,3.0,2,3205,0,0,2
296,2.0,1,527702,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,44.0,NaN,3.0,3.3,3.0,1,2208,0,0,1
297,1.0,1,529386,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,60.0,6.8,NaN,NaN,2.0,1,3205,0,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2

In [5]:
#Ajuste Para separar a coluna target

target_column = 23
y = df[target_column]
x_columns = df.columns.to_list()
x_columns.remove(target_column)
X = df[x_columns]
X

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,24,25,26,27
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,5.0,45.0,8.4,NaN,NaN,2.0,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,2.0,50.0,85.0,2.0,2.0,3.0,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,1.0,33.0,6.7,NaN,NaN,1.0,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,NaN,48.0,7.2,3.0,5.3,2.0,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,NaN,74.0,7.4,NaN,NaN,2.0,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,5.0,55.0,65.0,NaN,NaN,3.0,3205,0,0,2
296,2.0,1,527702,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,4.0,44.0,NaN,3.0,3.3,3.0,2208,0,0,1
297,1.0,1,529386,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,5.0,60.0,6.8,NaN,NaN,2.0,3205,0,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,4.0,50.0,6.0,3.0,3.4,1.0,2208,0,0,1
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,1.0,36.0,62.0,1.0,1.0,3.0,6112,0,0,2

##Respostas:

In [6]:
#Total missing
X.isnull().sum()

0       1
1       0
2       0
3      60
4      24
5      58
6      56
7      69
8      47
9      32
10     55
11     44
12     56
13    104
14    106
15    247
16    102
17    118
18     29
19     33
20    165
21    198
22      1
24      0
25      0
26      0
27      0
dtype: int64

## Respostas abaixo:

In [8]:
df_arbri = df

In [26]:
df_arbri.fillna(-100000000,inplace = True)

In [12]:
df_mediana = df

In [24]:
df_mediana.fillna(df_mediana.median(),inplace = True)

In [14]:
df_media = df

In [23]:
df_media.fillna(df_media.mean(),inplace = True)

In [16]:
df_endoftail = df

In [21]:
df_endoftail.fillna(df_endoftail.ffill().tail(1).iloc[0],inplace = True)

In [27]:
df_knn = df

In [28]:
knn_input = KNNImputer(n_neighbors=1)
knn_input.fit_transform(df_knn)

array([[2.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [2.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       ...,
       [1.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.30612e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34618e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00]])

In [29]:
df_knn

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,3.0,2.0,...,45.0,8.4,1.0,1.0,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,3.0,3.0,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,1.0,1.0,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,3.0,3.0,6.0,2.0,...,74.0,7.4,1.0,1.0,2.0,2,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,37.2,120.0,70.0,4.0,3.0,4.0,2.0,...,55.0,65.0,1.0,1.0,3.0,2,3205,0,0,2
296,2.0,1,527702,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,44.0,62.0,3.0,3.3,3.0,1,2208,0,0,1
297,1.0,1,529386,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,60.0,6.8,1.0,1.0,2.0,1,3205,0,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
299,1.0,1,534618,37.2,40.0,20.0,3.0,3.0,3.0,1.0,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2